---
- hosts: "localhost"
  tasks:
  - name: "Build ECS Service"
    cloudformation:
      stack_name: "waterorder-service"
      state: "present"
      region: "ap-southeast-2"
      disable_rollback: true
      template: "Service_cfn.yml"


